# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
    steps:
      - uses: actions/checkout@v2
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1
      - name: Terraform Init
        run: terraform init
      - name: Terraform plan
        run: terraform plan -var location="westeurope" -var resource_group="stgo-dsi-dp-test-rg" -var storage_name="stgodsidptestsa" -var service_plan_name="stgo-dsi-dp-test-asp" -var service_name="stgo-dsi-dp-test-service" -var mysql_server_name="stgo-dsi-dp-test-mysql" -var mysql_database_name="todo" -var mysql_firewall_name="stgo-dsi-dp-test-firewall"
      - name: Terraform apply
        run: terraform apply --auto-approve -var location="westeurope" -var resource_group="stgo-dsi-dp-test-rg" -var storage_name="stgodsidptestsa" -var service_plan_name="stgo-dsi-dp-test-asp" -var service_name="stgo-dsi-dp-test-service" -var mysql_server_name="stgo-dsi-dp-test-mysql" -var mysql_database_name="todo" -var mysql_firewall_name="stgo-dsi-dp-test-firewall"
